# 柴鼠兄弟 ETF觀看學習紀錄

2021年11月28日

5 探勘ETF0056 捕獲高股息十年不敗名單 聯詠 兆豐金 光寶科 蟬聯42季度 有0056 就有這三家 0056成份股 市值至少維持 250億以上

6 又暴跌 反向ETF 20210715 反向etf是一種 單日報酬商品 結論 反向ETF不適合做長期投資 僅適合短線操作 7 十大配息ETF排行～殖利率最高不是0050、填息最快的不是0056 20181024 有配息的都是原型ETF 0050 0051 - 0056 006201 006203 006204 利用 goodinfo 台灣股市資訊網 將所有ETF現金殖利率由高往低排

8 0056台灣高股息ETF最新成分股名單 2018年12月9日 每年六月 十二月例行更新持股名單 納入 國巨 技嘉 微星等 0056 每年配息一次

9 配息ETF費用率排行 有二隻比0050還低 公開說明書 一定要看 指數 1 追蹤何種指數 2 指數編撰方法 3 指數成份審閱和調整時間 * 股利 在etf中就是指 收益分配配息 0050每年六月 十二月進行配息 每年七月和一月公佈除息日和分配金額 （0056每年一次 9/30） 內扣費用 （受益人之權力及費用負擔）最重要是經理費和保管費 年度費用率 用來評估ETF的隱性成本 0056為 0.7- 0.8％ 0050 為0.42-0.44％ （006208 富邦台50 平均費用率 0.42％ 為最低） 00692 富邦公司治理 0.38％ 10 ETF股價怎麼追蹤指數？ ETF (exchanged Traded Fund) 指數股票型基金 拿股票換成ETF叫實物申購 拿ETF換回股票叫實物買回 2017年開始 主管機關已開放ETD可以採用現金申贖 法人可以用現金跟投信買500張ETF 或是買好500張ETF去跟投信換成現金 ETF 不能用股票的邏輯來看待 1 ETF籌碼非固定 隨時有新的籌碼 透過實物申贖加入股市 2 影響ETF股價最重要的因素 是淨值 也就是股價的表現

問題解答
1 開放型基金單位數不固定

11 下一個國民ETF是誰？ 選ETF的三大重點 1 淨資產（規模） 近30個營業日 淨資產低於一億元 ETF就會被中止信託契約（下市） ETF掛牌上市 資產至少要2億元 目前 100億以上有8家 佔6.8％ ETF下市 依照每單位淨值計算 把錢退回給投資人 （分配順序） ETF淨值很重要 他代表這款便當真正的價值 2 流動量（日成交量）500張以上 或是 （張數 * 100） 每日現成交量不到100張 約佔全國現有ETF的1/3 （36檔） 盡量選成交量 > 500張以上 3 成份 （關係到 能否配息 及 長期持有）股票 債券 期貨 僅股票型有配息

12 十大配息ETF排行 殖利率最高不是0050、填息最快的不是0056 2018年10月24日 一般公司七至九月除權息 發股利 > ETF > 發股利 給 ETF投資人 2018年 etf殖利率 前四名 0056（5.71％）0053元大電子（3.37％）0051元大中型100（3.27％）0050（3.07％） 10大配息etf填息天數 第一名 元大中型100（0051）16.2天 第十名 元大高股息（0056）99.4天 13 0056台灣高股息ETF最新成分股名單 2018年12月9日

14 ETF股價怎麼追蹤指數？關鍵在實物/現金申贖機制 2019年10月18日

15 下一個國民etf（跟第11集內容一樣）

16 ETF會像次貸泡沫嗎？ （1）底層資產不同 （2）沒有多重衍生 （3） 影響力仍小

17 原型ETF全台股就這21支2020年度總評比 原型ETF全台股 佔 16.8

市值型  台灣元大50 富邦台50 永豐台灣加權 元大中型100 富邦台灣中小
高息型
經營型
MSCI型 可以被納入MSCI成份 可得外資及大型基金的注意
產業型

選擇ETF 如果看得頭暈 先看基本四項 
規模 規模 20億以上
成交量 每日成交200張以上
殖利率 4％以上
費用率 低於1%

再去評估
成份
BETA
報酬率

18 台股ETF也有本益比了 Vanguard 早在官網公佈商品的本益比 例如追蹤 S&P500指數的VOO 此次元大公佈 股價淨值比 本益比 BETA值 ROE 現金股息率 年化波動度

EPS = 稅後淨利(繳完稅之後的淨利) / 股數(資本額/10) ＝ 平均每一股完稅之後還賺多少錢
        Earnings Per Share (每股稅後盈餘) 或是每股純益 每季為單位
        簡單講 EPS 就是賺的錢 除以股票數量
本益比 = 股價 / EPS , 在EFT就是 所有成份股總市值 / 所有成份股總盈餘 （適用原型ETF）
股價淨值比 = 成份股的總市值 / 成份股的總淨值 （以1為基準 高於1 ）ETF的成份都是高成長型公司
                股價淨值比自然比較高 00762元大未來 就是高成長型公司
BETA值 (看柴鼠 最佛系金控 )原則上  當BETA值 絕對值大於1越多 代表 相對於全市場波動越大
                                      當BETA值 絕對值低於1越多 代表 波動相對低
                                    如果是負值 代表和大盤相反
                                    （季線60MA）BETA值用三個月當作一個基準
ROA = 稅後淨利(繳完稅之後的淨利) / 資產(經濟資源) 
        Retrun On Asset 資產報酬率(整體資產的獲利能力)
        簡單說 就是公司投入多少的資源產生這樣的獲利
ROE ＝ 稅後淨利(繳完稅之後的淨利) / 淨值(股東權益)
        Return On Equality 股東權益報酬率
        因為公司的資產有部份可能是借貸來的錢 公司的資產 扣掉借來的錢 才是公司真正的錢 這就是 淨值
        淨值在會計科目中叫做 股東權益
        假設現在公司立刻 解散清算 資產和負債抵銷後 剩下的部份 就是每個股東 依照持股比例分配的權益

        2017年台灣上市公司的ROA(資產報酬率)ROE(股東權益報酬率)要擠進台股100強 
        ROA 要10%   ROE至少要20% 
        ** 但金融業和金控業因為資產的負債比有90%以上 所以不適用ROE(股東權益報酬率) 
        ** 要用能反應整體資產獲利能力的ROA(資產報酬率)才比較準確些
現金股息率 ＝ 近12個月股利 / 股價（移動現金股息率更貼切）
年化波動度 （衡量近一年ETF價格波動程度）數字越低 代表越穩

19 除了金融股還選什麼菜？從00742發現台客內需概念股 夯翻鼠FQ61 存股投資 00742 新光內需收益 追蹤 台灣指數公司 特選內需高收益指數（從此檔ETF中發現 台灣內部需求為主的概念股） 大型龍頭 台泥 統一 中華電 股利穩健 精誠 中鼎 裕日車 可寧衛 豐興 防禦抗壓 遠傳 台灣大 中保科

20 兆豐金和0056配息差不多 但ETF節稅效益卻有差- 關鍵在你的綜合所得稅級距 夯翻鼠FQ64 股利佔比

21 [美股ETF 海外券商 複委託]一張圖PK優缺 ⟪00757⟫尖牙股科技十強一檔全選

22 巴菲特-奧運-RCEP三大光環加持日股！用00645日本ETF追東證指數 一開門就到東京 柴鼠兄弟 商社 股神

23 00891半導體神山-季配息 台股ETF唯一聯發科權重高於台積電 柴鼠兄弟 中信關鍵半導體 00891 中國信託台灣ESG永續關鍵半導體ETF
